### DISCUSSION TITLE
How to Set minFileSize & minLengthMS Settings

### DISCUSSION THREAD

**Discussion by sameleff** [jlesage/docker-filebot#93] [Q&A] [answered]
Is there a way to turn off (or change) the default minimum file size and minimum file length settings?

I have several old (e.g. poor quality) episodes of Adventure Time that get skipped due to these settings. I found [this ](https://www.filebot.net/forums/viewtopic.php?t=9764)old forum article, but the options didn't effect anything when I set them as environment variables in my docker-compose file. Are there different commands for your fork?

**Comment by jlesage** [comment]
Did you try to set the `AMC_CUSTOM_OPTIONS` environment variable to something like `minFileSize=0 minLenghtMS=0`?

**Reply by sameleff** [reply]
I tried this morning but I don't know the proper formatting. Here is what I tried:

```
environment:
  - AMC_CUSTOM_OPTIONS:
    - minFileSize=0
    - minLengthMS=0
```
This resulted in an error that caused my docker-compose to fail before filebot could even start (services.filebot.environment.15 must be a string). In my code, "15" refers to the line with `- AMC_CUSTOM_OPTIONS`.

```
environment:
  - AMC_CUSTOM_OPTIONS=
    minFileSize=0
    minlengthMS=0
```
This allowed FIlebot to start, but it threw the following two errors:
`Argument[1]: File does not exist: /etc/services.d/amc/minFileSize=0`
`Argument[2]: File does not exist: /etc/services.d/amc/minLengthMS=0`

```
environment:
  - AMC_CUSTOM_OPTIONS=(minFileSize=0, minFlengthMS=0)
```
This resulted in a similar error as the 2nd run: `File does not exist: /etc/services.d/amc/(minFileSize=0, minLengthMS=0)

Any advice on formatting?

**Comment by jlesage** [comment]
It should be like this:

```
environment:
  AMC_CUSTOM_OPTIONS: minFileSize=0 minlengthMS=0
```

See https://docs.docker.com/compose/compose-file/compose-file-v3/#environment

**Reply by sameleff** [reply]
Hmmm. I tried that just now, but I get the same "file does not exist" error for both of the two custom commands. Here's my revised environment variable block if it helps:

```
environment:
      LANG: en_us.UTF-8
      TZ: America/New_York
      FILEBOT_GUI: 1
      WEB_LISTENING_PORT: 5800
      AMC_ENABLED: 1
      AMC_INTERVAL: 1800 #Time (s) between each invocation of the AMC script
      AMC_INPUT_STABLE_TIME: 10 #Time (s) during which properties (size, time, etc.) but be constant in the /watch folder before invoking the AMC script.
      AMC_ACTION: move #The action performed by the AMC script. Options are: test, copy, move, symlink, hardlink, keeplink, duplicate, clone.
      AMC_LANG: English
      AMC_MUSIC_FORMAT: '{plex}'
      AMC_MOVIE_FORMAT: '{plex} {"{edition-$$edition}"}'
      AMC_SERIES_FORMAT: '{plex} {"{edition-$$edition}"}'
      AMC_PROCESS_MUSIC: n
      AMC_INPUT_DIR: /storage/newmedia
      AMC_OUTPUT_DIR: /storage/outputmedia
      AMC_CUSTOM_OPTIONS: minFileSize=0 minLengthMS=0
```
