### ISSUE TITLE
Plex Editions Re-Naming not Working with AMC Script

### ISSUE THREAD

**Issue by sameleff** [jlesage/docker-filebot#91]
Here is my docker-compose file:

```
version: "3.8"
services:
  filebot:
    container_name: filebot
    image: jlesage/filebot
    ports:
      - 5800:5800
    volumes:
      - ./filebot_config:/config:rw
      - /mnt/n/newmedia:/watch:rw
      - /mnt/n/outputmedia:/output:rw
      - /mnt/n/testmedia:/storage:rw
    environment:
      - LANG=en_us.UTF-8
      - TZ=America/New_York
      - FILEBOT_GUI=1
      - WEB_LISTENING_PORT=5800
      - AMC_ENABLED=1
      - AMC_INTERVAL=1800 #Time (s) between each invocation of the AMC script
      - AMC_INPUT_STABLE_TIME=10 #Time (s) during which properties (size, time, etc.) but be constant in the /watch folder before invoking the AMC script.
      - AMC_ACTION=move #The action performed by the AMC script. Options are: test, copy, move, symlink, hardlink, keeplink, duplicate, clone.
      - AMC_LANG=English
      - AMC_MUSIC_FORMAT={plex}
      - AMC_MOVIE_FORMAT={plex} {"{edition-$edition}"}
      - AMC_SERIES_FORMAT={plex}
      - AMC_PROCESS_MUSIC=n
```
When I perform a manual rename using the web interface and using the same expression to rename movies (`{plex} {"{edition-$edition}"}`) it performs the match correctly.

When I run the AMC script after starting the docker container using the above docker-compose, it renames this file as such:
Original File: /newmedia/The Iron Giant (1999) {edition-Signature}
New Name: /outputmedia/Media/Movies/The Iron Giant (1999) {edition-}

Here are my logs if they help (In this run of the AMC script, I even tried re-naming the original file with an edition binding from the list of available options shown [here](https://www.filebot.net/forums/viewtopic.php?t=12668)...same issue):

```
Run script [fn:amc] at [Mon May 08 20:38:08 EDT 2023]

[PSA] Important Discussion of Proposed Changes:
https://www.filebot.net/forums/viewtopic.php?t=13406

Parameter: artwork = n
Parameter: music = n
Parameter: clean = y
Parameter: excludeList = /config/amc-exlude-list.txt
Parameter: movieFormat = {plex} {"{edition-}"}
Parameter: musicFormat = {plex}
Parameter: seriesFormat = {plex}
Parameter: animeFormat = {plex}
Argument[0]: /watch
Use excludes: /config/amc-exlude-list.txt (0)
Input: /watch/The Iron Giant {edition-Theatrical}.mkv
Group: {Movie=The Iron Giant (1999), Series=null} => [The Iron Giant {edition-Theatrical}.mkv]
Rename movies using [TheMovieDB]
Auto-detect movie from context [/watch/The Iron Giant {edition-Theatrical}.mkv]
[MOVE] from [/watch/The Iron Giant {edition-Theatrical}.mkv] to [/output/Movies/The Iron Giant (1999)/The Iron Giant (1999) {edition-}.mkv]
Processed 1 file
Clean clutter files and empty folders
Keep /watch (root folder)
Done ヾ(＠⌒ー⌒＠)ノ
```
